### ISSUE TITLE
Typo on FAQ section

### ISSUE THREAD

**Issue by aminick** [flexpool/frontend#409]
Discord member found typo

![image](https://user-images.githubusercontent.com/5182324/130904582-fafa3c38-2a11-4895-8c1e-c1d5b75bc3b7.png)

**Comment by indyramp** [comment]
I'll add a couple of corrections here for the Chia FAQ as well... 

1. Do I have to make new plots for Flexpool or FlexFarmer?

"with an -f plotter option rather than -c" should be "with a -p plotter option rather than -c" 

2. Does Flexpool charge a fee for every transaction?

"The only fee you will pay is the network transaction fee, that is static regardless of the transaction value." can be removed. Right now there are no transaction fees paid by the farmer for XCH transactions. 

3. New question to add:

**How do I change to a different pool server for my Chia farm?**

First of all, you should not need to do this unless you are seeing 500ms or higher ping times to the server, and maybe not even then. Chia is not as sensitive to network latency as Ethereum is. 

That being said, "changing" the pool server is technically leaving the pool and joining again. From the GUI, you would use the "Change Pool" button, changing to the "new" region server. From the CLI, you would leave the pool with "chia plotnft leave" and join the new one with "chia plotnft join"
