### ISSUE TITLE
Manual stats refresh button

### ISSUE THREAD

**Issue by AlexSSD7** [flexpool/frontend#95]

**Comment by march08** [comment]
@AlexSSD7  Which stats are we talking about? The header stats? I think it should be easy enough to implement polling with X minutes interval with some UI indicator

**Comment by AlexSSD7** [comment]
Not the header stats exactly, but the stats on the entire page.

The person who reported this attached a video recording of his use case:
https://cdn.discordapp.com/attachments/812127120377643028/832368919268425758/video0.mp4

**Comment by march08** [comment]
I'll try to understand why the page doesn't refresh on pull first

**Comment by jpbelo** [comment]
@march08 the pull down to refresh isn't a feature on safari.
To have pull down to refresh, you actually need to implement it on the site.
You can trick the page to not overscroll, and then highjack that to do a refresh.
(BTW, safari does not have overscroll-behavior implemented yet.)

An easier solution is probably to add a refresh page button. Or even better, a "reload data button". So instead of doing a page refresh you just recall the api and update the fields.

One last option, my preferred solution, is to set a timeout and update the data each minute. (similar to what hiveon has but instead of reloading the whole page, just do a fetch).
